# Generated by Django 3.1.2 on 2020-10-18 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_answered', models.IntegerField()),
                ('correctly_answered', models.IntegerField()),
                ('wrongly_answered', models.IntegerField()),
                ('quiz_date_time', models.DateTimeField(auto_now_add=True)),
                ('correct_answer', models.CharField(blank=True, default=None, max_length=100000000, null=True)),
                ('quiz_cat', models.CharField(blank=True, default=None, max_length=100000000, null=True)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
