# Generated by Django 3.1.2 on 2020-10-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='question',
            field=models.CharField(blank=True, default=None, max_length=100000000, null=True),
        ),
    ]
