# Generated by Django 3.1.2 on 2020-10-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_quiz', '0002_userdata_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='ques_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
